/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface User {
  id: number;
  fullName: string;
  email: string;
  phone: string;
  createdAt: string;
}

export interface AuthResponse {
  user: User;
}

export interface SignupInput {
  /** @minLength 1 */
  fullName: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  phone: string;
  /** @minLength 8 */
  password: string;
}

export interface LoginInput {
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  password: string;
}

export interface ErrorResponse {
  error: string;
}

export interface MessageResponse {
  message: string;
}

export interface Freelancer {
  id: number;
  name: string;
  skillCategory: string;
  location: string;
  rateGhs: number;
  bio: string;
  portfolioImageUrl?: string | null;
  email: string;
  phone: string;
  createdAt: string;
}

export interface FreelancerInput {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  skillCategory: string;
  /** @minLength 1 */
  location: string;
  /** @minimum 1 */
  rateGhs: number;
  /** @minLength 10 */
  bio: string;
  portfolioImageUrl?: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  phone: string;
}

export interface FreelancerListResponse {
  freelancers: Freelancer[];
}

export interface FreelancerResponse {
  freelancer: Freelancer;
}

export interface Property {
  id: number;
  title: string;
  description: string;
  location: string;
  monthlyRentGhs: number;
  bedrooms: number;
  bathrooms: number;
  amenities: string;
  landlordName: string;
  landlordContact: string;
  photoUrl?: string | null;
  availableDate: string;
  createdAt: string;
}

export interface PropertyInput {
  /** @minLength 1 */
  title: string;
  /** @minLength 1 */
  description: string;
  /** @minLength 1 */
  location: string;
  /** @minimum 1 */
  monthlyRentGhs: number;
  /** @minimum 0 */
  bedrooms: number;
  /** @minimum 1 */
  bathrooms: number;
  amenities?: string;
  /** @minLength 1 */
  landlordName: string;
  /** @minLength 1 */
  landlordContact: string;
  photoUrl?: string;
  /** @minLength 1 */
  availableDate: string;
}

export interface PropertyListResponse {
  properties: Property[];
}

export interface PropertyResponse {
  property: Property;
}

export interface CourseListItem {
  id: number;
  title: string;
  description: string;
  category: string;
  level: string;
  durationHours: number;
  instructor: string;
  coverImageUrl?: string | null;
  certificatePriceGhs: number;
  lessonCount: number;
  createdAt: string;
}

export interface Lesson {
  id: number;
  courseId: number;
  orderNum: number;
  title: string;
  content: string;
  createdAt: string;
}

export interface QuizQuestion {
  id: number;
  courseId: number;
  orderNum: number;
  question: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
}

export interface CourseDetail {
  id: number;
  title: string;
  description: string;
  category: string;
  level: string;
  durationHours: number;
  instructor: string;
  coverImageUrl?: string | null;
  certificatePriceGhs: number;
  lessonCount: number;
  createdAt: string;
  lessons: Lesson[];
  quizQuestions: QuizQuestion[];
}

export interface CourseProgress {
  id: number;
  userId: number;
  courseId: number;
  completedLessonIds: string;
  quizScore?: number | null;
  quizPassed: boolean;
  certificatePurchased: boolean;
  certificateName?: string | null;
  certificateId?: string | null;
  updatedAt: string;
}

export interface UpdateProgressInput {
  completedLessonIds: string;
}

export interface QuizAnswer {
  questionId: number;
  answer: string;
}

export interface QuizSubmissionInput {
  answers: QuizAnswer[];
}

export interface QuizResult {
  score: number;
  total: number;
  passed: boolean;
}

export interface ClaimCertificateInput {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  paymentReference: string;
}

export interface CertificateData {
  certificateId: string;
  courseTitle: string;
  recipientName: string;
  instructor: string;
  issuedAt: string;
}

export interface CourseListResponse {
  courses: CourseListItem[];
}

export interface CourseDetailResponse {
  course: CourseDetail;
}

export interface CourseProgressResponse {
  progress: CourseProgress | null;
}

export interface QuizResultResponse {
  result: QuizResult;
}

export interface CertificateResponse {
  certificate: CertificateData;
}

export type ListFreelancersParams = {
search?: string;
category?: string;
};

export type ListPropertiesParams = {
search?: string;
location?: string;
minPrice?: number;
maxPrice?: number;
bedrooms?: number;
};

