/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponse,
  CertificateResponse,
  ClaimCertificateInput,
  CourseDetailResponse,
  CourseListResponse,
  CourseProgressResponse,
  ErrorResponse,
  FreelancerInput,
  FreelancerListResponse,
  FreelancerResponse,
  HealthStatus,
  ListFreelancersParams,
  ListPropertiesParams,
  LoginInput,
  MessageResponse,
  PropertyInput,
  PropertyListResponse,
  PropertyResponse,
  QuizResultResponse,
  QuizSubmissionInput,
  SignupInput,
  UpdateProgressInput
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getSignupUrl = () => {




  return `/api/auth/signup`
}

export const signup = async (signupInput: SignupInput, options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getSignupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupInput,)
  }
);}




export const getSignupMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: BodyType<SignupInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: BodyType<SignupInput>}, TContext> => {

const mutationKey = ['signup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signup>>, {data: BodyType<SignupInput>}> = (props) => {
          const {data} = props ?? {};

          return  signup(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SignupMutationResult = NonNullable<Awaited<ReturnType<typeof signup>>>
    export type SignupMutationBody = BodyType<SignupInput>
    export type SignupMutationError = ErrorType<ErrorResponse>

    export const useSignup = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signup>>, TError,{data: BodyType<SignupInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof signup>>,
        TError,
        {data: BodyType<SignupInput>},
        TContext
      > => {
      return useMutation(getSignupMutationOptions(options));
    }

export const getLoginUrl = () => {




  return `/api/auth/login`
}

export const login = async (loginInput: LoginInput, options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginInput,)
  }
);}




export const getLoginMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: BodyType<LoginInput>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<LoginInput>
    export type LoginMutationError = ErrorType<ErrorResponse>

    export const useLogin = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: BodyType<LoginInput>},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options));
    }

export const getGetMeUrl = () => {




  return `/api/auth/me`
}

export const getMe = async ( options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<ErrorResponse>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<ErrorResponse>



export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<ErrorResponse>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getLogoutUrl = () => {




  return `/api/auth/logout`
}

export const logout = async ( options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {


          return  logout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>

    export type LogoutMutationError = ErrorType<unknown>

    export const useLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options));
    }

export const getListFreelancersUrl = (params?: ListFreelancersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/freelancers?${stringifiedParams}` : `/api/freelancers`
}

export const listFreelancers = async (params?: ListFreelancersParams, options?: RequestInit): Promise<FreelancerListResponse> => {

  return customFetch<FreelancerListResponse>(getListFreelancersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFreelancersQueryKey = (params?: ListFreelancersParams,) => {
    return [
    `/api/freelancers`, ...(params ? [params] : [])
    ] as const;
    }


export const getListFreelancersQueryOptions = <TData = Awaited<ReturnType<typeof listFreelancers>>, TError = ErrorType<unknown>>(params?: ListFreelancersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listFreelancers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFreelancersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFreelancers>>> = ({ signal }) => listFreelancers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFreelancers>>, TError, TData> & { queryKey: QueryKey }
}

export type ListFreelancersQueryResult = NonNullable<Awaited<ReturnType<typeof listFreelancers>>>
export type ListFreelancersQueryError = ErrorType<unknown>



export function useListFreelancers<TData = Awaited<ReturnType<typeof listFreelancers>>, TError = ErrorType<unknown>>(
 params?: ListFreelancersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listFreelancers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListFreelancersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateFreelancerUrl = () => {




  return `/api/freelancers`
}

export const createFreelancer = async (freelancerInput: FreelancerInput, options?: RequestInit): Promise<FreelancerResponse> => {

  return customFetch<FreelancerResponse>(getCreateFreelancerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      freelancerInput,)
  }
);}




export const getCreateFreelancerMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFreelancer>>, TError,{data: BodyType<FreelancerInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createFreelancer>>, TError,{data: BodyType<FreelancerInput>}, TContext> => {

const mutationKey = ['createFreelancer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createFreelancer>>, {data: BodyType<FreelancerInput>}> = (props) => {
          const {data} = props ?? {};

          return  createFreelancer(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateFreelancerMutationResult = NonNullable<Awaited<ReturnType<typeof createFreelancer>>>
    export type CreateFreelancerMutationBody = BodyType<FreelancerInput>
    export type CreateFreelancerMutationError = ErrorType<ErrorResponse>

    export const useCreateFreelancer = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createFreelancer>>, TError,{data: BodyType<FreelancerInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createFreelancer>>,
        TError,
        {data: BodyType<FreelancerInput>},
        TContext
      > => {
      return useMutation(getCreateFreelancerMutationOptions(options));
    }

export const getListPropertiesUrl = (params?: ListPropertiesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/properties?${stringifiedParams}` : `/api/properties`
}

export const listProperties = async (params?: ListPropertiesParams, options?: RequestInit): Promise<PropertyListResponse> => {

  return customFetch<PropertyListResponse>(getListPropertiesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPropertiesQueryKey = (params?: ListPropertiesParams,) => {
    return [
    `/api/properties`, ...(params ? [params] : [])
    ] as const;
    }


export const getListPropertiesQueryOptions = <TData = Awaited<ReturnType<typeof listProperties>>, TError = ErrorType<unknown>>(params?: ListPropertiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listProperties>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPropertiesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listProperties>>> = ({ signal }) => listProperties(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listProperties>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPropertiesQueryResult = NonNullable<Awaited<ReturnType<typeof listProperties>>>
export type ListPropertiesQueryError = ErrorType<unknown>



export function useListProperties<TData = Awaited<ReturnType<typeof listProperties>>, TError = ErrorType<unknown>>(
 params?: ListPropertiesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listProperties>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPropertiesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreatePropertyUrl = () => {




  return `/api/properties`
}

export const createProperty = async (propertyInput: PropertyInput, options?: RequestInit): Promise<PropertyResponse> => {

  return customFetch<PropertyResponse>(getCreatePropertyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      propertyInput,)
  }
);}




export const getCreatePropertyMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProperty>>, TError,{data: BodyType<PropertyInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createProperty>>, TError,{data: BodyType<PropertyInput>}, TContext> => {

const mutationKey = ['createProperty'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProperty>>, {data: BodyType<PropertyInput>}> = (props) => {
          const {data} = props ?? {};

          return  createProperty(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePropertyMutationResult = NonNullable<Awaited<ReturnType<typeof createProperty>>>
    export type CreatePropertyMutationBody = BodyType<PropertyInput>
    export type CreatePropertyMutationError = ErrorType<ErrorResponse>

    export const useCreateProperty = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProperty>>, TError,{data: BodyType<PropertyInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createProperty>>,
        TError,
        {data: BodyType<PropertyInput>},
        TContext
      > => {
      return useMutation(getCreatePropertyMutationOptions(options));
    }

export const getListCoursesUrl = () => {




  return `/api/courses`
}

/**
 * @summary List all courses
 */
export const listCourses = async ( options?: RequestInit): Promise<CourseListResponse> => {

  return customFetch<CourseListResponse>(getListCoursesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCoursesQueryKey = () => {
    return [
    `/api/courses`
    ] as const;
    }


export const getListCoursesQueryOptions = <TData = Awaited<ReturnType<typeof listCourses>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCourses>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCoursesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCourses>>> = ({ signal }) => listCourses({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCourses>>, TError, TData> & { queryKey: QueryKey }
}

export type ListCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof listCourses>>>
export type ListCoursesQueryError = ErrorType<unknown>


/**
 * @summary List all courses
 */

export function useListCourses<TData = Awaited<ReturnType<typeof listCourses>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCourses>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListCoursesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetCourseUrl = (id: number,) => {




  return `/api/courses/${id}`
}

/**
 * @summary Get course with lessons and quiz
 */
export const getCourse = async (id: number, options?: RequestInit): Promise<CourseDetailResponse> => {

  return customFetch<CourseDetailResponse>(getGetCourseUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCourseQueryKey = (id: number,) => {
    return [
    `/api/courses/${id}`
    ] as const;
    }


export const getGetCourseQueryOptions = <TData = Awaited<ReturnType<typeof getCourse>>, TError = ErrorType<ErrorResponse>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCourse>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCourseQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourse>>> = ({ signal }) => getCourse(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCourse>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCourseQueryResult = NonNullable<Awaited<ReturnType<typeof getCourse>>>
export type GetCourseQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get course with lessons and quiz
 */

export function useGetCourse<TData = Awaited<ReturnType<typeof getCourse>>, TError = ErrorType<ErrorResponse>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCourse>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCourseQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetCourseProgressUrl = (id: number,) => {




  return `/api/courses/${id}/progress`
}

/**
 * @summary Get current user progress for a course
 */
export const getCourseProgress = async (id: number, options?: RequestInit): Promise<CourseProgressResponse> => {

  return customFetch<CourseProgressResponse>(getGetCourseProgressUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCourseProgressQueryKey = (id: number,) => {
    return [
    `/api/courses/${id}/progress`
    ] as const;
    }


export const getGetCourseProgressQueryOptions = <TData = Awaited<ReturnType<typeof getCourseProgress>>, TError = ErrorType<ErrorResponse>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCourseProgress>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCourseProgressQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourseProgress>>> = ({ signal }) => getCourseProgress(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCourseProgress>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCourseProgressQueryResult = NonNullable<Awaited<ReturnType<typeof getCourseProgress>>>
export type GetCourseProgressQueryError = ErrorType<ErrorResponse>


/**
 * @summary Get current user progress for a course
 */

export function useGetCourseProgress<TData = Awaited<ReturnType<typeof getCourseProgress>>, TError = ErrorType<ErrorResponse>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCourseProgress>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCourseProgressQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateCourseProgressUrl = (id: number,) => {




  return `/api/courses/${id}/progress`
}

/**
 * @summary Update lesson completion progress
 */
export const updateCourseProgress = async (id: number,
    updateProgressInput: UpdateProgressInput, options?: RequestInit): Promise<CourseProgressResponse> => {

  return customFetch<CourseProgressResponse>(getUpdateCourseProgressUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProgressInput,)
  }
);}




export const getUpdateCourseProgressMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCourseProgress>>, TError,{id: number;data: BodyType<UpdateProgressInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCourseProgress>>, TError,{id: number;data: BodyType<UpdateProgressInput>}, TContext> => {

const mutationKey = ['updateCourseProgress'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCourseProgress>>, {id: number;data: BodyType<UpdateProgressInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCourseProgress(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateCourseProgressMutationResult = NonNullable<Awaited<ReturnType<typeof updateCourseProgress>>>
    export type UpdateCourseProgressMutationBody = BodyType<UpdateProgressInput>
    export type UpdateCourseProgressMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Update lesson completion progress
 */
export const useUpdateCourseProgress = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCourseProgress>>, TError,{id: number;data: BodyType<UpdateProgressInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateCourseProgress>>,
        TError,
        {id: number;data: BodyType<UpdateProgressInput>},
        TContext
      > => {
      return useMutation(getUpdateCourseProgressMutationOptions(options));
    }

export const getSubmitQuizUrl = (id: number,) => {




  return `/api/courses/${id}/quiz`
}

/**
 * @summary Submit quiz answers and get result
 */
export const submitQuiz = async (id: number,
    quizSubmissionInput: QuizSubmissionInput, options?: RequestInit): Promise<QuizResultResponse> => {

  return customFetch<QuizResultResponse>(getSubmitQuizUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      quizSubmissionInput,)
  }
);}




export const getSubmitQuizMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitQuiz>>, TError,{id: number;data: BodyType<QuizSubmissionInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof submitQuiz>>, TError,{id: number;data: BodyType<QuizSubmissionInput>}, TContext> => {

const mutationKey = ['submitQuiz'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitQuiz>>, {id: number;data: BodyType<QuizSubmissionInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  submitQuiz(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubmitQuizMutationResult = NonNullable<Awaited<ReturnType<typeof submitQuiz>>>
    export type SubmitQuizMutationBody = BodyType<QuizSubmissionInput>
    export type SubmitQuizMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Submit quiz answers and get result
 */
export const useSubmitQuiz = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitQuiz>>, TError,{id: number;data: BodyType<QuizSubmissionInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof submitQuiz>>,
        TError,
        {id: number;data: BodyType<QuizSubmissionInput>},
        TContext
      > => {
      return useMutation(getSubmitQuizMutationOptions(options));
    }

export const getClaimCertificateUrl = (id: number,) => {




  return `/api/courses/${id}/certificate`
}

/**
 * @summary Claim a certificate after passing the quiz
 */
export const claimCertificate = async (id: number,
    claimCertificateInput: ClaimCertificateInput, options?: RequestInit): Promise<CertificateResponse> => {

  return customFetch<CertificateResponse>(getClaimCertificateUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      claimCertificateInput,)
  }
);}




export const getClaimCertificateMutationOptions = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimCertificate>>, TError,{id: number;data: BodyType<ClaimCertificateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof claimCertificate>>, TError,{id: number;data: BodyType<ClaimCertificateInput>}, TContext> => {

const mutationKey = ['claimCertificate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof claimCertificate>>, {id: number;data: BodyType<ClaimCertificateInput>}> = (props) => {
          const {id,data} = props ?? {};

          return  claimCertificate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClaimCertificateMutationResult = NonNullable<Awaited<ReturnType<typeof claimCertificate>>>
    export type ClaimCertificateMutationBody = BodyType<ClaimCertificateInput>
    export type ClaimCertificateMutationError = ErrorType<ErrorResponse>

    /**
 * @summary Claim a certificate after passing the quiz
 */
export const useClaimCertificate = <TError = ErrorType<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof claimCertificate>>, TError,{id: number;data: BodyType<ClaimCertificateInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof claimCertificate>>,
        TError,
        {id: number;data: BodyType<ClaimCertificateInput>},
        TContext
      > => {
      return useMutation(getClaimCertificateMutationOptions(options));
    }

